examples/meson.build

There were some missing dependencies to the createZimExample compilation.

Fix compilation of createZimExample.

---

src/search_iterator.cpp
src/xapian/htmlparse.cc
src/xapian/htmlparse.h
src/xapian/myhtmlparse.cc
src/xapian/myhtmlparse.h

Even if the HtmlParser is fully private, it use a static variable.
If the code of the HtmlParser is also used in another project, the
two static variables will conflict.
By using a namespace we avoid the potential conflict.
Fixes #18

Enclose the HtmlParser in a namespace to avoid conflict.

---

meson.build
src/meson.build

That's bad, project version were never used when compiling the library.

Fix libversion compilation.

---

include/zim/file.h
include/zim/search.h
src/file.cpp
src/search.cpp

In suggestion mode, the flag FLAG_PARTIAL
(https://xapian.org/docs/apidoc/html/classXapian_1_1QueryParser.html#ae96a58a8de9d219ca3214a5a66e0407eae0b632c2f797fc7ae53c444f104072c7)
will be added to the default flag for the queryparser.
If the embedded database has been indexed with a separated title namespace,
the search will be only in this namespace. Else the search is made in
all the database.

Add suggestion mode to the search.

---

src/search.cpp

Zim files created before 2017-03 doesn't have a language metadata in the
database.
But the database was created stemming the content. So we need to stem
our request also.
For example, "Maladie" will be indexed using the stemmed term "malad".
If we don't stem our request, xapian will not found the "maladie" term
in the database, and will return no result.
If we stem our request, we search for "malad" and everything works.
So we need a language. zim file itself store a language metadata, so
let's use it if the database has no metadata.

Correctly stem term for the research for "old" zims.

---

include/zim/file.h
include/zim/fileimpl.h
include/zim/fstream.h
src/fileimpl.cpp
src/search.cpp

We cannot search in multipart zim. So do not search.
Fixes kiwix/kiwix-tools#65
The search will not working, but kiwix-serve will not crash.

Do not search in embedded data base if zim is multipart.

---

src/file_reader.cpp

Correctly terminate the lzma steam at buffer decompression.

---

src/buffer.cpp

`MAP_POPULATE` is not defined on apple platform, so do not use it.
Fixes #46

Do not use MAP_POPULATE symbol on apple platform.

---

include/zim/buffer.h
include/zim/file_compound.h
include/zim/file_part.h
include/zim/file_reader.h
src/buffer.cpp
src/cluster.cpp
src/dirent.cpp
src/file_reader.cpp
src/fileimpl.cpp
src/writer/cluster.h

As a zim files may be larger than 4GB, we need 8 bytes len integer
to store size or offset in a zim file.
`std::size_t` is not the same depending if the architecture is
32 bits (4 bytes) or 64 bits (8 bytes).
On the other side, we are properly declaring `offset_type` in zim.h to
always be 8 bytes whatever the architecture is.
So, let's use `offset_type` instead of `std::size_t`.
Fixes kiwix/kiwix-tools#76

Use the correct type to store size/offset.

---

src/fileimpl.cpp

Commit 0b6604c wrongly changes the way we find the beginning of the offset.
It can lead to libzim not finding the first article on some namespace in
some case.
Revert it.
Fix kiwix/kiwix-tools#95

Revert back some wrongly changes on getBeginNamespaceOffset

---

include/zim/search.h
src/search.cpp

If the embedded xapian database has geo localisation information, we
can filter search result in a range around a position using
`set_georange` methode.

All zimlib to do geo query if avalaible in xapian database.

---

src/fileimpl.cpp

The `bufferDirentZone` is a temporary buffer to store the raw
memory for a Dirent comming from the zim file.
We have to protect it when we use it in different threads else
dirent may be initialized with corrupt data.
Shame on me, I have defined the associated lock in the header but never
use :/
Fix kiwix/kiwix-tools#108.

Correctly protect temporary thread shared buffer.

---

src/buffer.h
src/cluster.cpp
src/debug.h
src/file_reader.cpp
src/file_reader.h

`execinfo` is not available with mingw and apple platform
(https://www.gnu.org/software/gnulib/manual/html_node/execinfo_002eh.html),
so print the callstack only on linux.

Print better assert message and the callstack on assert failing.

---

include/zim/search.h

`search_iterator::InternalData` is declared as a `struct`, so we must use
`friend struct`.
Fix #95.

Use friend struct instead of friend class.

---

include/zim/blob.h

If we want to initialize a `Blob` with a `operator=`, the members of the
`Blob` must not be `const`.
This is not a change in the api as `_data` and `_size` are private.

Allow blob to be assigned with operator=

---

travis/compile.sh

`mesontest` command is deprecated since meson `0.42.0` and it is broken
with last release (`0.44.0`). (mesonbuild/meson#2761)

Use 'meson test' command instead of deprecated 'mesontest'.

---

src/xapian/myhtmlparse.h

Recent versions of llvm are now compiled with '-Woverloaded-virtual`
option. (http://llvm.1065342.n5.nabble.com/Woverloaded-virtual-td5478.html)
This option raise a warning if a virtual method is overloaded in a chill
class. The compiler raise a warning because of the potential mistake of
overloading the method instead of overwriting it.
Fix #95
By explicitly bringing the definition of `parse_html` in `MyHtmlParser`,
we avoid the warning.

Provide parse_html definition from HtmlParser in MyHtmlParser.

---

src/search.cpp

We need to correctly initialize all field of a search instance.
Fixes kiwix/kiwix-tools#119

Correctly initialize a search instance.

---

src/fileimpl.cpp

If there is no checksum in the zim file, the end of the last cluster
is the end of the file, not the checksumPos.
Fix kiwix/kiwix-tools#150

Do not assume there is a checksum in zim when reading cluster.

---

meson.build
src/meson.build

Instead of manually adding -Wall -Werror, set werror=true which will set the same in a cross-platform way.
Also declare a dependency so libzim can be used as a subproject.

meson: Use werror=true and declare a dependency

---

src/levenshtein.cpp
src/levenshtein.h
src/meson.build
src/search.cpp

By default xapian sort search result using relevance using the BM25
algorithm.
This alogrithm calculate the relevance using a "complex" calculation based
on the number of terms in each document, the number of terms in the
query, the number of documents, ...
This works pretty well with full documents but when we search in the
title namespace, this is not relevant at all.
Most titles are pretty short and the query is most of the time one term
only. In this case, all title are very close in number of term and all
contain only one term matching the query. Relevances are very closed and
most of the time irrelevant.
This commit sort the document using the Levenshtein distance of the
document titles to the query string. The search results are pretty more
relevant this way !
The levensthtein …

Improve ordering of suggestions search results.

---

src/search_iterator.cpp

If the url stored in the embedded index database is not absolute,
make it so.
Fix kiwix/kiwix-lib#110

Search should return absolute url.

---

src/fileimpl.cpp

The full url can be if the form of `N/url` or `/N/url`.
We must handle both.
Fix kiwix/kiwix-tools#165

Accept absolute url in findx.

---

test/cluster.cpp

Compressing with lzma can take a looootttt of time.
Do not try to compress big buffer.
As the `str_content` is now bigger, we must use the right type to store
the size variable.

[TEST] Do not try to compress big cluster.

---

src/writer/cluster.cpp

`toLittleEndian` will use the type of the first argument (`o.v`) to
know the size of value and so, how many bytes to write.
But offset_t is always a 64bits integer and OFFSET_TYPE may be a 64bits or
a 32bits integer.
So `toLittleEndian` may write out of buffer.

Cast the value to OFFSET_TYPE.

---

src/meson.build
test/meson.build

We need a RPATH to allow binaries and libraries to find other libraries.
We need this because :
- We are not installing libraries in the default (system) directories and
- We cannot change the LD_LIBRARY_PATH in macos.

Fix RPATH of libzim.

---

src/writer/zimcreator.cpp

mimetype should never be null.
In normal case, caller code should ensure that `article->getMimeType()`
doesn't return a empty mimetype.
But it is better to not trust user code.
See openzim/zimwriterfs#48

Ensure mimetype is not null.

---

src/writer/zimcreator.cpp

`CompareTitle` will use the index to get the correct dirent in `dirents`.
As the indexes in `titleIdx` are "url indexes", the `dirents` must be
sort by url before sorting `titleIdx`.
The last time `dirents` was sorted was by aid in `resolveRedirectIndexes`,
so, `CompareTitle` were comparing title of wrong dirents.
Fix openzim/zimwriterfs#55

Correctly sort titles' array.

---

src/file_part.cpp
src/search.cpp
src/tools.cpp
src/tools.h

All our strings are (and must) be utf8 encoded.
We just need to convert the filepath to utf-16 (wchar_t) right before
opening the file using `_wopen`.
Client code must pass utf8 encoded string to libzim.
See http://utf8everywhere.org/
As opening a file is now a bit more complex that just run `open` and we
need to open a file at sereval place, create the tool functon `openFile`
to open file correctly.
Fix #74

Correctly open file in windows.

---

src/buffer.cpp

off_t is a signed int. So max is INT32_MAX, not UINT32_MAX.

Fix check of maximum offset for mmap.

---

meson.build

zlib try to include "unistd.h" if _LARGEFILE64_SOURCE is defined.
If we are compiling on windows platform, "unistd.h" is not present and
compilation fails.

Define _LARGEFILE64_SOURCE only if not on windows.

---

src/search.cpp

XapianDatabase will always close the file descriptor, even in case of
error. Do not try to close it ourselves.
On windows, the `close` on a invalid file descriptor make the application
crash.

Do not close the databasefd in case of error.

---

src/search.cpp

Otherwise there's no separation and it all gets jumbled
together.

Add newline to end of "Try to open..." message

---

src/fileimpl.cpp

On very small zim, 256 bytes is sometime to big.
Fix #194

Do not try to read after the end of the file when reading dirent.

---

src/cluster.cpp
src/cluster.h
src/file_reader.cpp
src/file_reader.h
src/fileimpl.cpp
test/cluster.cpp

We were assuming that cluster were written sequentially. But even if
it is what is made by libzim (reference implementation), this is not in
the spec and other may not write them sequentially.
So we have to detect the size of the cluster differently:
- For uncompressed cluster, we have to read the cluster header.
As this is not compressed, the size of the cluster in the header is the
same of the (zim) buffer containing the cluster.
- For compressed cluster, we cannot use the cluster header because
1. It is compressed
2. The size in the header is the uncompressed size, not the size of
the compressed header.
In fact, there is no way to know the size of the compressed buffer
without decompressing the data until we reach the end of the
compression stream. So we have to decompress the data, …

Do not fail if cluster are not written sequentially.

---

src/meson.build

Rpath is not needed to run installed binaries. Most of GNU/Linux
distributions strictly forbid it.
See also:
* https://lintian.debian.org/tags/binary-or-shlib-defines-rpath.html
* https://wiki.debian.org/RpathIssue
* https://docs.fedoraproject.org/en-US/packaging-guidelines/#_beware_of_rpath

Removed Rpath from compiled binaries

---

src/writer/queue.h
src/writer/zimcreator.cpp
test/uuid.cpp

Mingw doesn't implement it. So, we should not use it.
I suppose that it was working before because mingw package for debian trusty
simply no provides a "thread" header.
We may face to include the native "thread" header.
Has sleep was only use for creator and test and we never try to launch
zimwriterfs on windows, we never face the problem.

Do not use this_thread::sleep.

---

src/tools.cpp
src/tools.h
src/writer/queue.h
src/writer/zimcreator.cpp
test/uuid.cpp

On mingw32 `this_thread::sleep` is not implemented but `microsleep` is
not implemented on windows :/
We have to use a intermediate tool function to sleep.

Revert Do not use this_thread::sleep.

---

travis/install_deps.sh

Update python3 (from 3.6 to 3.7) take on looot of time on the CI
(~half an hour).
Python 3.6 is enough so, do not update it.

Do not update python3 on macos CI.

---

include/zim/file.h
src/file.cpp

This will avoid memory leak when client forget to delete the Search object.

Return a unique_ptr instead of a raw pointer when creating a search.

---

include/zim/article.h
include/zim/file.h

- Windows header define the max macro :/
- cl complains about the not defined ZimDumper. And we don't need it.

Fix windows compilation.

---

meson.build
test/meson.build

gtest may not be available if it is not system installed and meson is
run with `--wrap-mode=nodownload`.
We must meson without download in flatpak because run the build in a
container without network access.

Do not fail if gtest is not found.

---

.codecov.yml

Codecov should ignore 'test' and 'examples' directories

---

src/levenshtein.cpp

By using a generic min function we are internally doing a loop on the
tuple.
This improves the suggestion search of kiwix-tools almost by a factor
of 2!!

Do not use std::min on an tuple.

---

test/iterator.cpp

`Article::getIndex()` return a `zim::article_index_type`, who is an
unsigned int.
Let's use the right type to avoid warning (and error with -Werror) when
comparing values.

Use the correct type for our test vector.

---

README.md
include/zim/zim.h
meson.build
src/cluster.h
src/compression.cpp
src/compression.h
src/config.h.in
src/file_reader.cpp
src/meson.build
src/writer/cluster.cpp
test/cluster.cpp

Fix for #84.
These changes introduce zstd as an optional dependency for libzim. **The default compression method stays the same (lzma) regardless of whether libzim was compiled with zstd enabled**.
The implementation is based on most basic stream-based Zstd compression API. The compression level is set to the highest value without any means of controlling it from outside.
A new unit test `ClusterTest.read_write_clusterZstd` was created as a clone of `ClusterTest.read_write_clusterLzma`.
As additional testing zim-tools was built with the default compression method set to zstd. The file `wikipedia_en_climate_change_nopic_2020-01.zim` (31MB) found under `tests/data` was successfully recreated with slight (470KB) reduction in size. The runtime of recreation with zstd compression is slower …

Support for Zstd compression

---

include/zim/file.h
include/zim/fileiterator.h
src/file.cpp

Commit fc8949b change the default order of `const_iterator`.
It breaks the `File::find` function as the find function find by url
and create a iterator using the default order.
As the order change, the iterator is broken.
This commit remove the default value of the `const_iterator`, so creating
a iterator need an explicit order.
The `File::begin` create the iterator using the "default" `ClusterIterator`
order.
This also add a method `File::beginByUrl` to allow user code to access
an iterator by url.
Fix kiwix/kiwix-lib#339

Fix find function.

---

src/writer/creator.cpp
src/writer/creatordata.h

We were doing the following in `Creator::finishZimCreation`:
- Wait for workers to finish their tasks
- Send a nullptr per worker as new tasks in the task queue
- [When a worker get a null tasks from the task queue,
it quit its infinit loop (and so the thread ends).]
- We finish the zim creation and delete the creatorData (and so the
task queue also).
What may happen is that the last steps of zim creation are really quick
and we delete the creatorData before all worker threads get the
null task from the queue. In this case, worker try to use the task queue
but it is deleted => SIGSEV.
By adding a `thread_join` we ensure that threads have totally end.
(Checking that all tasks have been made is not enough).

Correctly wait for the threads' termination before finishing zim creation.

---

src/writer/creator.cpp
src/writer/creatordata.h

`tmpfname` is unused and not initialized.
Index path name must be based on `basename`, not `tmpfname`.
Fix #https://github.com/openzim/mwoffliner/pull/1097#issuecomment-625232734

Fix the path of the temporary index during writing.

---

include/zim/writer/article.h

Those two class are totally useless and are not used.
We should have removed them a long time ago.

Remove ArticleSource and Category.

---

src/cluster.cpp
src/file_reader.h
src/fileimpl.cpp

Using the `getDirent` is too complex for our use case here where we just
want the cluster number.
Directly reading the two integers we need should be pretty more efficient.
Fix #344

Better implementation of the creation of the cluster ordered list.

---

src/compression.cpp
src/compression.h
test/compression.cpp
test/meson.build

Add test on the compression/decompression algorithm and fix few (important) issues.
One of the bug leads us to create invalid zim files (kiwix/kiwix-tools#389).
The problem appears when the compressed size was bigger that the initial allocated buffer (1024Kb).
This is especially triggered by the issue (openzim/mwoffliner#1183).

Fix compression

---

test/meson.build

This allows slow architectures such as emulated riscv64 in Ubuntu to successfully finish the build process.
https://launchpad.net/ubuntu/+source/zimlib/6.1.3-4ubuntu2
also, please have a look at:
https://bugs.debian.org/964196
containing more details on the issue

Update meson.build, increase test timeout

---

examples/createZimExample.cpp
include/zim/writer/creator.h
src/writer/creator.cpp
src/writer/creatordata.h

Will fix #360
The default compression type is still LZMA. Client code can create ZIM files with a different compression type by passing an extra argument to the `zim::writer::Creator` constructor.
An alternative was to make libzim pick up the compression type from an environment variable, in which case no changes would need to be made in client code and all tools would automatically benefit from this enhancement. However in a slack discussion with @kelson the choice wad made in favour of hard control over the compression method via the libzim API.

Compression type can be passed to zim::writer::Creator

---

test/cluster.cpp
test/dirent.cpp
test/header.cpp
test/meson.build
test/tempfile.cpp
test/tempfile.h

1. In `cluster`, `dirent` and `header` unit-tests there was some duplication of code related to temporary files. That duplication was eliminated with the introduction of `test/tempfile.h`. This change also fixes a potential leak of temporary files when an exception is thrown during the execution of the unit-test.
2. Besides, under POSIX-like OS-es creation of temporary files now respects the value of the `TMPDIR` environment variable (if the latter is not set, `/tmp` is assumed). This change enables to run unit-tests in a `tmpfs` filesystem (e.g. `/run/user/USERID`) which reduces the wear of SSD storage on modern hardware during a quick-paced edit-save-build-and-test development mode.
It should be slightly more convenient to review this PR commit-by-commit.

Better management of temporary files in unit-tests

---

.github/workflows/package.yml

Occasionally some distros will fail to build, e.g. right
now unstable and groovy are broken because of 
<https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=965033>.
Setting fail-fast: false will allow those that do work to
continue to build so a failure in one place doesn't
affect everything else.

PPA: Set fail-fast: false

---

.github/workflows/package.yml
debian/control
debian/rules

Two commits:
PPA: Stop building for Ubuntu eoan, its EOL
Launchpad no longer accepts uploads for eoan.
While we're at it, restore the PPA as a build dependency for the package. I
had earlier removed it on the basis that zimlib didn't depend on any local
packages, but if we need to backport any extra dependencies (like I want to
for a newer debhelper), then we need to rely on the PPA. Also it's easier to
keep all the CI definitions the same anyways.
----
debian: Sync with proper Debian package
* Switch to debhelper 13
* Bump build timeout via `meson test` (this will fix the few remaining timeouts I see on launchpad builds which is using some really resource limited/slow amd64 builders...)

PPA: Drop eoan and sync with proper Debian package

---

test/data/meson.build

Will fix #388 
The `copy` keyword argument of `configure_file()` first appears in meson 0.47. Now performing file copy via python.

Support for meson versions before 0.47

---

test/zimfile.cpp

Besides checking that multi-part ZIM files are handled correctly, the new unit-test also significantly increase the coverage of libzim. Actually, that's the main reason why I added it: while working on optimization of caching in libzim I found out that libzim's own unit-tests don't cover relevant code (`zim::FileImpl::getCluster()`), so I had to test those changes via kiwix-lib. However, though the new unit-test exercises `zim::FileImpl::getCluster()`, a separate unit-test focusing on cache access patterns is still needed (this one was simply a low-hanging fruit).
Regarding `Article::getPage()`, it turned out that data needed for meaningful operation of `Article::getPage()` misses from the test ZIM files, so I wonder if it makes sense to keep my second commit (a separate unit test for …

Added a unit-test checking correct handling of multipart ZIM files

---

src/file_compound.h
test/zimfile.cpp

Fixes #398.
Under MacOS the implementation of `std::map::equal_range()` makes assumptions about the properties of the key comparison function and abuses the `std::map` requirement that it must contain unique keys. As a result, when a map `m` is queried with an element `k` that is equivalent to more than one keys present in `m`, `m.equal_range(k).first` may be different from `m.lower_bound(k)` (the latter one returning the correct result).
This PR must be merged after #387 (by first rebasing the fix_for_issue398 branch onto master).

Fix for issue #398

---

include/zim/file.h
src/file.cpp

This reverts commit 3dac58aeb929b39fe5800b9b9869f31fbf758196, addressing one of the screwups described in https://github.com/openzim/libzim/pull/393#issuecomment-677670354

Revert "[API change] Dropped zim::File::getOffset()"

---

src/concurrent_cache.h
src/fileimpl.cpp
src/fileimpl.h
src/lrucache.h

This PR addresses #379 only with respect to the cluster cache.
The fix eliminates the possibility of the same cache entry being generated simultaneously from parallel threads (resulting in waste of CPU time and memory). It comes at the cost of slightly more expensive cache hits (a `std::shared_future` object, which is roughly equivalent to a shared pointer is created for every cache access). This is unavoidable if we want the cache access to be absolutely safe.
I wonder if the same approach should be applied to the dirent cache.

Improvement of concurrent access to cluster cache

---

src/fileimpl.cpp
src/fileimpl.h
test/impl_find.cpp
test/meson.build

Working on the new libzim api, I had to test the `findx`, `getNamspaceBeginOffset` and `getNamespaceEndOffset` of the `FileImpl`.
As this is a pretty self contained change and not related to the new api, I create a new PR.

Test findx

---

src/fileimpl.cpp
src/fileimpl.h

When using `zim::article_index_t`, MSVC fails to find the right
implementation to use for `!=` operator between:
- Internal implementation in some `xmemory` header
- libzim implementation `operator!=` defined for `zim::article_index_t`.
By using the plain `zim::article_index_type` (an alias for uint32_t),
there is no more conflict.
We do the same for `cluster_index_t`.
Fix #414

Fix compilation of lru_cache on windows.

---

src/cluster.cpp
src/cluster.h
src/file_reader.cpp
src/file_reader.h
src/fileimpl.cpp
src/reader.h
test/cluster.cpp

This PR contains some groundwork for #411, however it should be useful on its own even if the latter PR is not merged.
Save for the last commit, the changes are merely of refactoring nature. The last commit corrects a bug in the cluster unit-test that allows an empty (or, more generally, undersized) blob returned by `Cluster::getBlob()` to pass the check.
As is usual for a sequence of relatively small refactoring changes, it is recommended to review this PR commit by commit.

Groundwork for partial/incremental decompression of clusters

---

src/buffer.cpp
src/cluster.cpp
test/bufferstreamer.cpp

This is a tentative fix of issue #427

Fixed Cluster::getBlob() for 32-bit platforms

---

src/fileimpl.cpp
src/fileimpl.h
test/impl_find.cpp

Fixes #407
The first commit of this PR is borrowed from #408, the second one is just an [earlier review comment](https://github.com/openzim/libzim/pull/382#discussion_r461154489) put into life, which automatically fixed the problem with `getNamespaceEndOffset()`.

Fixed getNamespaceEndOffset()

---

src/narrowdown.h
test/dirent_lookup.cpp

There was a bug in #430 - `zim::NarrowDown::getRange()` failed to locate the last item (entered via `zim::NarrowDown::close()`). This bug was caught by a zim-tools unit tests [CI run](https://github.com/openzim/zim-tools/pull/169/checks?check_run_id=1317019271). For some reason in my build tree the unit-tests of zim-tools don't run:
```
$ (cd BUILD_native_static/zim-tools && meson test -v)
ninja: Entering directory `~/Kiwix/builddir/BUILD_native_static/zim-tools'
ninja: no work to do.
No tests defined.
```

Fix for NarrowDown failing to locate the last item

---

src/meson.build
src/tools.cpp
src/writer/creatordata.h
src/writer/workers.cpp

Xapian is optional, we msut be able to compile without it.
While libzim compile without xapian, we have NOT tested that search api
and creator don't break when used without xapian.
This technically allow us to build libzim without xapian and this is needed to have a (first) libzim CI on windows.
But, as already said, it doesn't not enforce libzim works correctly without xapian.
Future PR will fix that.
See #423

Fix compilation on libzim without xapian.

---

src/fileimpl.cpp
src/narrowdown.h
src/tools.cpp
src/writer/creatordata.h
src/writer/workers.cpp
test/dirent.cpp
test/tools.cpp
test/tools.h
test/zimfile.cpp

This is a series of small fix when compiling on windows.
These where not known as we are not testing libzim on windows for now.
(Future PR will fix this point).
The commit 19b8727 is pretty important as it fix a potential crash on windows with libzim .

Fix windows

---

debian/control

PPA: Drop zlib1g-dev dependency

---

meson.build
src/concurrent_cache.h
src/debug.h
src/file_reader.cpp
src/fileimpl.cpp
src/fileimpl.h
src/writer/cluster.cpp
src/writer/cluster.h
src/writer/creator.cpp
src/writer/creatordata.h
src/writer/queue.h
src/writer/workers.cpp
src/xapian/htmlparse.cc
test/tools.h
test/zimfile.cpp

This PR remove strong dependency on pthread.
We use c++11 thread library which uses native thread and mutex api.
We still use pthread on linux but it allow use to don't use a wrapping pthread library on Windows.

No pthread

---

.github/script/build_libzim.cmd
.github/workflows/ci.yml
meson.build
subprojects/liblzma.wrap
subprojects/zstd.wrap

This add a CI on windows (msvc compiler).
lzma and zstd dependencies are build using meson wrap file system.
The wrap patch archives are generated from projects https://github.com/kymeria/liblzma and https://github.com/kymeria/zstd which contains the patches I apply to the meson build system.
These patches will be send upstream.
Depends of #443 
Fix #357

CI windows

---

src/fileimpl.cpp

Fixes #456 
This is an easy fix, however it won't show up in zim-tools until openzim/zim-tools#196 is merged (zim-tools still depends on the old libzim API, its compilation is broken and I don't know of any kiwix configuration & release management procedure of backporting a bugfix).

Title index check allows duplicate titles

---

.github/script/build_libzim.cmd
.github/workflows/ci.yml
include/meson.build
include/zim/meson.build
include/zim/zim.h
meson.build
meson_options.txt
src/meson.build
src/search.cpp
src/search_internal.h
src/search_iterator.cpp
src/writer/creatordata.h
src/writer/xapianIndexer.h

Simply remove the search api if libzim is compiled without xapian (related to #423).
The writer part is not changed. It will be better handled with implementation of https://github.com/openzim/libzim/issues/397

Better deactivate xapian support.

---

src/entry.cpp

Since libzim is path-first, it makes more sense to display the path on error message rather than the index.
Found in https://github.com/openzim/python-libzim/pull/82

Using path in Entry error message

---

src/archive.cpp
src/tools.cpp
test/find.cpp
test/parseLongPath.cpp

Fixes #477 
If a `path` of length 1 is passed and qualifies as a namespace character, return `(ns, "")`

Fix parseLongPath() to handle namespaces

---

src/tools.cpp

Mentioning the function explicitly as `std::min<unsigned int>`.

Fixes #489 Mentioning function explicitly

---

meson.build
src/buffer_reader.cpp
src/file_reader.cpp
test/archive.cpp
test/meson.build
test/reader.cpp
test/tools.cpp
test/tools.h

It is technically valid to read a zero sized at offset zero on a
zero sized reader.
The real assertion is that don't read past the end of the reader so
only `ASSERT(offset.v+size.v, <=, _size.v);` is needed.
This happen when reading a zim file with empty content and we don't
use mmap (on windows).
The cluster create a sub-reader of 0 size for the content and when
we try to read the 0 size content on the reader, we hit the ASSERT.
If we use mmap, we don't read from the reader, we create a mmap and
everything is fine.
The crashing assert is the one from FileReader but the logic is the
same for the BufferReader.
Fix kiwix/kiwix-lib#448

Allow reading of zero sized data on zero sized reader.

---

src/_dirent.h
src/dirent.cpp
src/dirent_accessor.cpp
src/dirent_accessor.h
src/dirent_lookup.h
src/direntreader.h
src/fileimpl.cpp
src/fileimpl.h
src/meson.build
src/narrowdown.h
test/dirent.cpp
test/dirent_lookup.cpp

This is the first PR corresponding to the split of #466
~~Based on #483 (not really needed for this PR but will be for the next, based on this one)~~ (merged in master)
- This change the architecture of the code as #466 does but do not change the creation behavior.
- Cherry-pick the `DirentReader` created by @veloman-yunkan in PR #430.
- ~~Add tests on zim creation.~~ (moved in #493)

Better dirent access (reading)

---

src/meson.build
src/writer/_dirent.h
src/writer/clusterWorker.cpp
src/writer/clusterWorker.h
src/writer/creator.cpp
src/writer/creatordata.h
src/writer/handler.h
src/writer/workers.cpp
src/writer/xapianHandler.cpp
src/writer/xapianHandler.h
src/writer/xapianIndexer.cpp
src/writer/xapianIndexer.h
src/writer/xapianWorker.cpp
src/writer/xapianWorker.h
test/creator.cpp
test/meson.build

This is the second part of the split of the PR #486.
This PR concentrate on the writing part and introduce the direntHandler.
Comments in #486 has been answered (either as comment here or by a "fixup!" commit).

Introduce a generic dirent/item handler in the writer.

---

test/find.cpp

Iterating over the range and ensuring consistency of `entry.getIndex()` with `count`. Testing presence of all entries in the range.

Compare indices of entries to remove test warnings

---

src/file_compound.cpp
src/file_compound.h
src/file_part.h
src/fs_windows.cpp
src/fs_windows.h
test/cluster.cpp
test/creator.cpp
test/reader.cpp

This constructor is buggy as it create a FD that should be destructed
differently that a FD created from a `HANDLE`.
We use it only in cluster's test so we can remove it.
Fix #478

Remove `zim::windows::FD:FD(int fd)`

---

src/writer/cluster.cpp

If the limit is 4Gb, it is better to set the max size to 4Gb.
I haven't made a real performance test but "cluster" unittest runs around 20% faster (from 6s to 4,7s)
Fix #455

Use a bigger chunk size to write clusters.

---

src/writer/creator.cpp
src/writer/creatordata.h
src/writer/xapianHandler.cpp
test/creator.cpp

Fixes #502 
`".zim"` extension is not automatically added to the output file path if it is not provided by the user in the input.

Fixes #502 File name consistent with input provided

---

src/fileheader.cpp
src/fs_windows.cpp
src/writer/creator.cpp
test/creator.cpp
test/header.cpp
test/tools.cpp

The bug comes from the fact that windows silently replaces `\n` by `\r\n` if we open the file "normally" (in text mode).
Fix #507
First commit is not necessary (windows replaces **silently**), but it is better to have it anyway.
(I've pushed the branch in two steps to have the CI run on the two last commits).

Fix zim file creation on Windows.

---

include/zim/writer/item.h
src/writer/defaultIndexData.h
src/writer/item.cpp
src/writer/xapianHandler.cpp
src/writer/xapianWorker.cpp
src/writer/xapianWorker.h
test/suggestion.cpp

Make the default indexer index data (content and title) only if it is html.
Change the way the indexData is created :
Before :
- We were creating a contentProvider (for the content) in main thread and read it in worker thread.
- We were creating a IndexData, initialize it (from a new contentProvider) in a worker thread
- To create the IndexData in the worker thread, we keep a reference to the item in the worker thread, so the item is used/destructed later.
Now:
- We are creating a contentProvider (for the content) in main thread and read it in worker thread.
- We are creating a IndexData (from a new contentProvider) in the main thread and we are initialize it (and read content from contentProvider) in a worker thread.
- We do not keep a reference to the item in worker thread. Once we …

Index data only if it is html by default and change how indexdata is created.

---

src/search.cpp
src/writer/xapianIndexer.cpp
test/suggestion.cpp

This pr is in continuation with #492
Fixes #509
Search with `OP_PHRASE` as the default operator
We are not providing higher weightage to `subquery_phrase`. The way this works is, suppose for a particular document, `subquery_and` gives a weightage `A` and `subquery_phrase` gives a weightage `B`. When we join these two queries with `OP_OR`, the net weight of this document becomes `A+B`. So this is why we are not losing any of the document which we used to get with only a single query. We are promoting the documents with terms in the correct order with the added weight of `subquery_phrase`. We have to do it because using only `subquery_phrase` makes the search too exclusive.
before:
```
$ kiwix-search -v --suggestion wikipedia_en_all_mini_2021-01.zim "the wolf of "
Performing suggestion …
```

Improve phrase search suggestions

---

src/search.cpp
src/writer/xapianHandler.cpp
src/writer/xapianIndexer.cpp
src/writer/xapianIndexer.h
test/suggestion.cpp

Fixes #276 
The motive of this pr is to allow efficient collapsing of duplicate entries(redirects) and to index target paths for redirect entries. If we have three entries like:
1. `Article Target`, `testPath`
2. `Article Redirect 1`, `redirectionPath1`, redirect to Article Target
3. `Article Redirect 2`, `redirectionPath2`, redirect to Article Target
Then a suggestion query  "Article" should return {`Article Target`}. That is, articles with the same path are collapsed and the article that is left is the most relevant one.
The changes included in this pr are
- Creating a new value slot `targetPath` in the index to store path/redirectPath of the entries.
- Set `targetPath` as the collapse key if it is available in the index.
- Add unit tests supporting the changes and explaining behavior …

Filter duplicates entries(redirections) in search suggestions

---

src/search.cpp
test/suggestion.cpp

Fixes #474 
We used to have collapse based on `title` value slot of documents in the suggestion search. This is a feature we do not want to keep. Though this is already not working after the merge of #515 (collapse on `targetPath` override this), the code is still there and should be removed. We only want to perform collapse based on `targetPath`. 
The changes included in this pr are
- Add unit tests that handle the case of different articles with the same title as mentioned in the ticket.
- Removes the unwanted title collapse on suggestion search.

Remove collapse based on title

---

src/writer/xapianIndexer.cpp

Fixes #417 
We do not use any operation that requires the use of a xapian term list. Removing it makes our indexes a bit leaner. Refer discussion on the linked issue for more info.
Changes included in this PR:
- Use `Xapian::DB_NO_TERMLIST` flag along with `Xapian::DB_CREATE_OR_OVERWRITE` to create xapian database

Create Xapian::WritableDatabase with DB_NO_TERMLIST Flag

---

src/constants.h
src/search.cpp
src/writer/xapianIndexer.cpp
test/suggestion.cpp

Fixes #510 
The solution employed in this PR is different from what was discussed on the ticket. There are some fundamental issues when we tweak the behavior of Xapian::Query in order to achieve anchoring, these are:
- `OP_PHRASE` search becomes uncontrollably tight. The query then matches **only** those documents that begin at the 0th position of the title and hence, skips a lot of relevant search results that occur in the middle of the title.
- Any query made with operators that use the position of terms matches all the documents in the index. That is, even in case of an empty query, `OP_PHRASE` matches all the documents.
In this PR, we are forcing the documents to have an `ANCHOR_TERM` "0posanchor" at the beginning of titles. This offers much more flexibility and ease of implementation …

Introduce anchor term to titles index

---

.github/workflows/ci.yml

Brew changes its backend. We must update it before using it.

[CI] Update brew before installing packages.

---

include/zim/search_iterator.h
src/search_iterator.cpp
src/writer/xapianIndexer.cpp
src/writer/xapianWorker.cpp
test/archive.cpp
test/search.cpp
test/suggestion.cpp

Fixes #523 
There is a compatibility issue when reading new zim files with older libzim used by some kiwixes. Older libzim still uses the convention where the namespace is not hidden from the path. Hence it fails to load items from the paths stored in new zim file indexes. The solution is to index the `fullPath` with namespace as the data of documents in the xapian index. This will make older libzim happy. We already have a compatibility layer in newer libzim that handles the old path convention with namespace, we just modify search iterator `get_path`(formerly `get_url`) to do the same.
The changes included in this pr are:
- Index `fullPath` in xapian title index.
- Index `fullPath` in xapian ft index.
- Introduce a new database metadata `data` that signifies what is contained as "data" …

Use full path as data of documents in the xapian index for compatibility of new zim files with older libzim

---

src/tools.cpp
src/writer/defaultIndexData.h
src/xapian/myhtmlparse.cc
test/defaultIndexdata.cpp
test/meson.build
test/suggestion.cpp
test/tooltesting.cpp

`countWord` was returning 1 for empty string.
This is a simple way to count word. But it is only use for statistic
about document. Actual count doesn't have to be exact.

Fix default html parsing.

---

src/search.cpp
test/suggestion.cpp

Fixes #537
> @maneeshpm This PR demonstrates a issue discovered during the work on kiwix/kiwix-lib#488 (for more details see commit https://github.com/kiwix/kiwix-lib/pull/488/commits/e5399be066c05b3f065d7d4542c48a0d4fa721e2). The workaround utilized in the said PR doesn't work for libzim out-of-the-box because it breaks some unit tests.
> 
> Would you mind taking over this PR and completing it?
Fixes #536 
The issue is Xapian queryparser does not work with `OP_PHRASE`/`OP_NEAR` as the default operator on certain kinds of queries. To fix this, we can change the default operator to `OP_OR` and bind the terms in a subquery that is created using query constructor with `OP_PHRASE` to handle the phrasing.
The changes included in this PR are:
- Add a unittest `nonWordCharacters` to suggestions. …

Non-word symbol friendly suggestions

---

src/meson.build
src/writer/counterHandler.cpp
src/writer/counterHandler.h
src/writer/creator.cpp
src/writer/handler.h
src/writer/titleListingHandler.h
src/writer/xapianHandler.h
test/creator.cpp

Counter metadata

---

scripts/download_test_data.py
src/archive.cpp
src/fileimpl.cpp
src/fileimpl.h
test/archive.cpp
test/find.cpp
test/iterator.cpp
test/meson.build
test/search.cpp
test/tools.cpp
test/tools.h

This PR somehow invalidate #531
(Moving the zim file in a different repository is still a open idea. But it can be done after this PR. Although it would be pretty useless. Adding the binary files to git will grow the total git repository size even if we remove them just after).
First commits prepare a bit the tests tools to be prepared to test several "same" test files.
After we add the new test files (which can be replaced by the download presented in #531)
Then we update the tests for the new test files.
It also "cherry-pick" #518 which now because obsolete.

Add zim files in the "new" format as testing data.

---

src/writer/defaultIndexData.h

On Appveyor, cl.exe include the wrong "tools.h".
It works on linux/github because meson add the "src" directory to the
include path.
On Appveyor there is probably another "tools.h" in the include directories
and we include the wrong one.
The correct way to include "tools.h" is to use relative path.

Fix build on Windows.

---

src/writer/cluster.cpp
test/cluster.cpp
test/tools.h

Should fix #551 (though this is speculative, since the change wasn't validated on the ZIM file of that crash report).
1. The `ClusterTest.read_write_extended_cluster` unit-test was modified to demonstrate the alleged problem causing the crash reported in #551.
2. Then the problem was fixed.
3. However the modified unit-test revealed a Windows-only bug in the `zim::unittests::write_to_buffer()` function. That bug was always triggered by the test, however its effects went unnoticed because the test wasn't elaborate enough. This bug was fixed too.
4. The `ClusterTest.read_write_extended_cluster` unit-test was further improved, so that it can catch similar bugs in the future.

Fixed zim::writer::Cluster::addContent()

---

test/meson.build
test/search.cpp
test/search_iterator.cpp
test/suggestion.cpp
test/tools.cpp
test/tools.h

Fixes #546 
Changes contained this PR:
- Move helper code `TempZimArchive` & `TestItem` to tools for better usability.
- Add some unit tests for the search iterator.

Add unit test for search iterator

---

include/zim/search.h
include/zim/search_iterator.h
src/search.cpp
src/search_internal.h
src/search_iterator.cpp
test/archive.cpp
test/search.cpp
test/search_iterator.cpp
test/suggestion.cpp

Fix #463, #516, #471.
Related to https://github.com/kiwix/kiwix-tools/issues/97
First commits roughly change the API to have a correct public API (but somehow wrong internal structures).
Later commits fix the internal structures to have something correct.
The main idea is to have :
- A `Searcher`, wrapping a xapian database.
- A `Search`, wrapping a particular query on the xapian database.
- A `SearchResult`, a set of result (range) corresponding to the `Search`.
We keep the iterator, but now we iterate over the `SearchResult`
We also introduce a `Query` object, describing a query (from user point of view), not associated to any database.

Rethink search API to fix several issues.

---

include/zim/writer/creator.h
src/compression.h
src/constants.h
src/writer/creator.cpp
src/writer/creatordata.h

- Rename minChunkSize/minClusterSize to clusterSize.
- Better doc string
- Change default value.
- Set the `creatorData::clusterSize` in the constructor.
. No need for setter/getter
. No need to have another default value.
- The already existing `creatorData::clusterSize` was not used,
let's use it instead of `minChunkSize`.
Fix #553

Better clusterSize configuration.

---

include/zim/search_iterator.h
src/search_iterator.cpp
test/search_iterator.cpp

Fixes #556 
Currently, users have to maintain a vector of Zim archives to track the archive from which a particular result is retrieved. Having a search iterator method `get_zimId` can let the user get the UUID of the archive from the search result itself.
Changes included in this PR:
- Adds the method `search_iterator::get_zimId()`
- Adds a test case to confirm this behavior

Add a new method search_iterator::get_zimId

---

src/search.cpp
src/search_internal.h
src/search_iterator.cpp
test/search_iterator.cpp

Fixes #86 
We address this issue by introducing a new member variable `m_stemmer` that stores the stemmer used for parsing queries by the `InternalDataBase::m_queryparser`. We use this stemmer as a parameter in `Xapian::MSet::snippet` which fixes this issue.
The changes included in this PR are:
- Adds a unit test `stemmedSearch` that demonstrates the expected behavior
- Introduce a member variable `m_stemmer`
- Use `m_stemmer` as a parameter while generating the snippet

Fix snippet highlighting for stemmed terms

---

src/compression.cpp
src/compression.h
src/concurrent_cache.h
src/decoderstreamreader.h
src/lrucache.h
subprojects/zstd.wrap
test/lrucache.cpp

If somehow `Decoder::stream_run_decode` fails,
`m_decoderState.avail_out` will never be updated and we are in a
infinite loop.
We must exit the loop at a moment.
Raising a exception may crash the user code if it doesn't catch it.
For kiwix-serve, we will return a 500 error code but we will still be
running.
See kiwix/libkiwix#515

Check decompression status in DecoderStreamReader.

---

meson.build
src/compression.cpp
src/concurrent_cache.h
src/config.h.in
src/fileimpl.cpp

The max level (22) set a huge windowSize (128Mb).
It if far too much and we don't even need it (most of our compressed
content is about 1Mb).
By setting a level of 19, the windowSize is 8Mb and
the compression ratio is relativly equivalent.
From lzbench https://github.com/inikep/lzbench the ratio is
24.88 for level 22 and 25.33 for level 18.
See kiwix/libkiwix#515

Lower zstd compression level.

---

include/zim/item.h
src/item.cpp

Needed by openzim/zim-tools#194
`Article::getClusterNumber()` was removed by #454. The work on multithreading of zimcheck (that was already in progress then) relied on that functionality, in order to process items from the same cluster in the same thread. This PR restores the said functionality as ZIM_PRIVATE API.

Restored Item::getClusterIndex()

---

include/zim/archive.h
include/zim/writer/item.h
scripts/download_test_data.py
src/archive.cpp
src/fileimpl.h
test/archive.cpp
test/iterator.cpp
test/tools.h

Fix #514 
This PR is base on #540 mainly to reuse the test data and avoid two branch with parallel test data versions.
In consequence, of this PR, new test data is generated (to have correctly set front articles)
The corresponding PR on zim-tools side is https://github.com/openzim/zim-tools/pull/246 and zim-testing-suite v3.0 alpha has been updated.

Better methods to get number of entries in a zim archive.

---

include/zim/archive.h
include/zim/writer/creator.h
scripts/download_test_data.py
src/archive.cpp
src/tools.cpp
src/tools.h
src/writer/creator.cpp
test/archive.cpp
test/creator.cpp
test/tooltesting.cpp

Remove favicon API and replace it by illustration methods.
We have decided with @kelson42 to not implement resolution fallback for this PR. Has I had already implemented a small fallback algorithm, I've keep it commented as reference.
It is not to be reviewed as the exact algorithm will probably change.
We need new zim file with the correct illustration entry. I've made a prerealase of zim-testing-suite with them (https://github.com/openzim/zim-testing-suite/releases/tag/v0.3-alpha). v0.3-alpha is made using this branch and https://github.com/openzim/zim-tools/pull/241
codecov is a bit under 90% has we don't test the fallback if there is no illustration/favicon at all in the zim file.

Add support of `M/Illustration` metadata in zim file.

---

include/zim/uuid.h
src/uuid.cpp
test/uuid.cpp

Fixes #581 
This PR adds a method `Uuid::to_str()` to Uuid. It combines the existing methods and directly returns a string cast for the uuid.
Changes included in this PR:
- Add method `Uuid::to_str()`
- Add a unit test for `Uuid::to_str()`

Add to_str() method to Uuid

---

src/search_iterator.cpp
test/search_iterator.cpp

Fixes #584 
SearchIterator::getTitle() should return the actual title of the entry rather than returning it from the valuesmap which is unaccented.

Fix getTitle to return the actual title

---

.github/workflows/package.yml

Groovy reaches its end of life.
Failing CI is https://github.com/openzim/libzim/actions/runs/1071601511
@legoktm please confirm we can remove groovy packages.

Do not build packages for groovy distribution (20.10)

---

src/compression.h

This is a fix of bug introduced with commit a7201ce.
Fix #578

[Compression] Correctly try to reallocate only when no output data.

---

include/zim/search.h
src/search.cpp
test/search.cpp

Fixes #596 
I propose we should follow the same convention as used by Xapian for consistency. That is, rather than keeping the second argument of `Search::getResults(start, end)` as `end` of range, we should use `maxResults` as the second argument. This way:
`getResult(start, maxResults)` will return results in the range `(start, start + maxResults)`
This makes use of API much easier and will require just a documentation fix. We need to fix the rest of the projects accordingly(even though they still work and won't break after this change) for which issues are being created.

Fix documentation of getResults

---

include/zim/writer/creator.h
src/writer/creator.cpp

Remove temporary files when we call finishZimCreation.

---

src/search.cpp
src/writer/xapianWorker.cpp
test/search_iterator.cpp
test/suggestion_iterator.cpp

Fixes #606 by reverting 3508e103072c4abcff9c721b88c1f9a9e12cbb3b
This was updated in order to "fix" stemming while building the add suggestion api pr. It is not required now since the api is completely built and we should revert the commit since it breaks back compatibility.

Revert updation of stemming strategy

---

include/zim/writer/item.h
src/writer/item.cpp

The basic idea was to store the created indexData's `shared_ptr` to
avoid creating it twice.
But the contentProvider may store a reference to the item, especially
when it reference content stored in the item (as it is the case for
`SharedStringContentProvider`.
This commit remove any storage of the created indexData.
This break the loop but at the cost of creating twice the indexData.
Will fix #618
The follow up of this PR will be the issue #620

Break reference loop in `Item`.

---

src/search.cpp
src/suggestion.cpp

Forcing xapian to check 1 documents is not enough and it may still leads to wrong results.
This is difficult to know which is the good number to put here, between a small number to avoid too many checks and a big number to force a accurate result.
10 seems to work for now, at least for small results set as used in tests.
This fix the unit test bug in python-libzim https://github.com/openzim/python-libzim/runs/3672830814
I ask for a favor here and do not add a specific unit test in libzim.
It would need to add a new content in openzim/zim_testing_suite and the change is pretty well contained, I don't see how it could break things.

For xapian to check 10 documents when asking for empty mset.

---

include/zim/writer/creator.h
test/creator.cpp

Specify the charset (UTF-8) in the default mimetype for addMetadata() so that readers can display it properly.
Similar to https://github.com/openzim/python-libzim/pull/119/commits/ebe062fcf5830f2040c2f409bb91919a399d91f5

Charset-aware default mimetype for addMetadata

---

include/zim/archive.h

Updating doc so it's clear what we get from `getIllustrationSizes()`

Docstring mentioning that width is returned for illustration size

---

src/suggestion.cpp
src/suggestion_internal.h
test/suggestion.cpp
test/suggestion_iterator.cpp

Fixes #644 
Suggestions module had several flaws which mainly arose from insufficient testing of reusability. This PR aims to address the following issues:
- Bad configuration of default parse operator
The default_op for the query parser is already being set during the initialization of database. The reconfiguration in `SuggestionDataBase::parseQuery()` is redundant and wrong. We should parse suggestion queries only with `OP_AND` and `OP_PHRASE` to ensure relevant suggestions.
This bad-configuration bug came from a buggy separation of suggestions and FT search and it didn't cause any issue till now since we were passing the first query with the default OP set during initialization. But it surfaced during the implementation of caching since we were now using the bad-reconfiguration.
- …

Switch default_op for query parser to OP_AND

---

src/archive.cpp
src/fileimpl.cpp
src/fileimpl.h

This PR implements the suggestion contained in https://github.com/kiwix/libkiwix/issues/643#issuecomment-990968425 and thus may be considered a fix for PR kiwix/libkiwix#643.
On old ZIM archives (using the old namespace scheme) `Archive::getRandomEntry()` returns an entry from the namespace "A".

Returning of random entry from namespace A

---

include/zim/meson.build
include/zim/version.h
include/zim/zim.h
meson.build
src/meson.build
src/version.cpp

Fixes #452 
Global idea is to build something similar in libkiwix and then call zim::versions() and/or kiwix::versions() in end-user tools like kiwix-desktop, kiwix-tools, etc.

Dependences version

---

src/dirent_lookup.h
src/fileimpl.cpp
src/fileimpl.h
test/dirent_lookup.cpp

This PR (originating from https://github.com/openzim/libzim/pull/647#discussion_r769655786) replaces the custom binary search in `FileImpl::findxByTitle()` by another DirentLookup object configured to work with dirents sorted by title.

More generic DirentLookup (able to perform by-title search too)

---

src/fs_unix.cpp

The previous PR (#667) was merged before I could improve it. Hence another small PR.

Even more informative error message

---

src/writer/creator.cpp
test/creator.cpp

Fixes openzim/zim-tools#289
Clusters owned by `CreatorData` are used in the worker threads. If the `CreatorData` destructor is executed as a result of stack unwinding caused by an exception raised before `CreatorData::quitAllThreads()` is called from `Creator::finishZimCreation()`, then the worker threads are still running and should be stopped by the `CreatorData::quitAllThreads()` call from `CreatorData::~CreatorData()`. However, that must happen *before* the clusters are destroyed.

Fixed CreatorData destructor

---

.github/workflows/ci.yml

The dependencies and meson crossfile are generated by kiwix-build on
macos-latest. We must use the same image.

Run the macos CI on macos-latest (macos-11)

---

include/zim/writer/item.h
src/writer/xapianHandler.cpp
src/writer/xapianWorker.cpp
src/writer/xapianWorker.h

Do not call `hasIndexData` and `getTitle` in the main thread.
- Default implementation of `hasIndexData ` need to parse the content and we don't want to parse the content in the main thread.
- Default implementation of `getTitle` do not need to parse the content but it is better to move the call in another thread for consistency.
Fix #683

Do not call `hasIndexData` in the main thread.

---

src/search_iterator.cpp

Working on https://github.com/kiwix/libkiwix/issues/769 (which is about suggestion), I've found this important improvement (about search).
`MSet::snippet` is more complex than it seems.
Xapian does some kind of complex algorithm to find the best text subset to
select. It does this by calculating the score/ranking of each term in the
text. To do so, it has to evaluate the terms in the context of the whole
mset and so, load "lot" of data from the database.
The perfect is the enemy of the good.
By removing the SNIPPET_EXHAUSTIVE flag, xapian evaluate less and return
(far more) quicker.
(https://xapian.org/docs/apidoc/html/classXapian_1_1MSet.html#a4797ae2295f88e49a9f76e3b89c21d88aea6a34a9c66720a44d5969ed47ca8edb)
Generated snippet is different, but still valid.
Do not search for exhaustive …

Do not search for exhaustive SNIPPET.

---

.github/workflows/ci.yml
src/fileimpl.cpp
src/fileimpl.h

Fixes #671 
`std::call_once` [is buggy](https://github.com/openzim/libzim/issues/671#issuecomment-1170979900):
1. It doesn't play well with musl libc - an exception thrown by the callable results in SIGABRT even if there is a handler for it higher
in the call stack.
2. With `glibc` an exceptional execution of `std::call_once` doesn't unlock the mutex associated with the `std::once_flag` object.

Got rid of std::call_once usage

---

include/zim/entry.h
src/entry.cpp
test/archive.cpp

Needed for openzim/zim-tools#312
`Entry::getRedirectEntryIndex()` is functionally equivalent to `Entry::getRedirectEntry().getIndex()`. However, the latter involves access to the dirent of the target entry. When only the index of the target entry is of interest, unnecessarily loading the target dirent may turn sequential disk IO (when iterating entries by their native order) to somewhat random disk IO. The new method is devoid of that drawback.

Added Entry::getRedirectEntryIndex()

---

src/writer/xapianIndexer.cpp
src/writer/xapianIndexer.h

Transactions are used to regroup modifications together and be sure that
they are either written all together in the database or not at all.
But here we don't care about coherence of the database. Either we succeed
to write index all documents or we have fail all the process.
And we never read the database will we are creating it.
On top of that, transaction probably prevent xapian to automatically
commit the modifications and so we are keeping everything in memory and
commit in fs only at the end of the process.
By removing transactions, we let xapian handle commits "correctly".
By default xapian will commit every 10000 documents.
This can be changed with the env var XAPIAN_FLUSH_THRESHOLD
See https://xapian.org/docs/apidoc/html/classXapian_1_1WritableDatabase.html#acbea2163142de795024880 …

Remove transaction system from xapian indexer.

---

src/fileimpl.cpp
src/fileimpl.h

1. memory usage of `FileImpl::m_articleListByCluster` has been halved
2. general purpose O(NlogN) sorting algorithm was replaced with a counting sort approach (with O(N) time complexity).

Optimization of the first call of zim::Archive::iterEfficient()

---

.github/workflows/ci.yml
README.md
include/zim/error.h
include/zim/writer/creator.h
src/writer/cluster.cpp
src/writer/clusterWorker.cpp
src/writer/clusterWorker.h
src/writer/creator.cpp
src/writer/creatordata.h
src/writer/workers.cpp
src/writer/workers.h
src/writer/xapianHandler.cpp
src/writer/xapianHandler.h
src/writer/xapianWorker.cpp
src/writer/xapianWorker.h
test/error_in_creator.cpp
test/meson.build

~~This is a draft PR, just to track the branch.~~ Now ready to review
Fixes #475
Fixes https://github.com/openzim/python-libzim/issues/153

Thread exception

---

include/zim/entry.h
include/zim/item.h
src/entry.cpp
src/item.cpp

The opportunity for this easy optimization was noticed while evaluating the proposal to get rid of the dirent cache (#438). This change aligns with that proposal since it reduces the need for that kind of cache (making `Entry` serve as the cache for `Item`).
--- 
For a client of libzim the only way to create an `Item` object is through `Entry::getItem()` or `Entry::getRedirect()` (the latter relying on the former to deliver the final result).
Before this change, `Entry::getItem()` performed (via the `Item` constructor) an extra call to `FileImpl::getDirent(entry_index_t)`. Now the result of that operation that is readily available in the source `Entry` object is reused.

Optimization of Entry::getItem()

---

include/zim/archive.h
src/archive.cpp
src/tools.cpp
src/tools.h
test/archive.cpp
test/counterParsing.cpp
test/meson.build

Fix #729 
Code is based on getArchiveMediaCount in libkiwix.
`readFullMimetypeAndCounterString` and `parseASingleMimetypeCounter` are copied from libkiwix, without modification.

Introduce Archive::getMediaCount

---

include/zim/suggestion_iterator.h

Private constructor of `SuggestionItem` doesn't buy us anything, but poses problems for unit testing.
This PR is needed for kiwix/libkiwix#843

Made constructor of SuggestionItem public

---

include/zim/tools.h

`ENABLE_XAPIAN` is a internal define.
The public define (and the one to check) is `LIBZIM_WITH_XAPIAN`.
Fix #739

Correctly test for `LIBZIM_WITH_XAPIAN` instead of `ENABLE_XAPIAN`.

---

.github/workflows/ci.yml

Looks like ninja depends on default brew python which is now python 3.11 but the action tries to link to 3.9.
See #743

Don't specify python version in Brew link

---

.github/workflows/ci.yml

Now than kiwix-build compile all our dependencies we can compile for wasm in our CI.

Add a CI for wasm.

---

test/error_in_creator.cpp

Wait for few (milli)seconds is not enough.
Thread may run sooner or later than expected.
New testiing checks that the following appears **in order**:
- One or several calls without throwing an error
- One (and only) call throwing an `AsyncError`
- Following calls always throwing a CreatorStateError.
- Last call always throws a exception.
Fix #747

Be more tolerant to threads scheduling in unit tests.

---

include/zim/entry.h
include/zim/item.h
src/entry.cpp
src/item.cpp

This reverts commit 1aca07b29d3936f4928b861d9184ac449a6e75d5.
While this change was technically correct, it removes the methods and breaks the ABI.
We shouldn't had introduced it in the 8.1 branch.
Once accepted and merged in `br_8.1`, a patch release `8.1.1` will be made. See https://github.com/openzim/python-libzim/issues/160

Revert "Optimization of Entry::getItem()" (on br 8.1)

---

include/zim/entry.h
include/zim/item.h
src/entry.cpp
src/item.cpp

This reverts commit 1aca07b29d3936f4928b861d9184ac449a6e75d5.
While this change was technically correct, it removes the methods and breaks the ABI.
We shouldn't had introduced it in the 8.1 branch.
We revert it for now as the current `main` branch introduce no api break. The change will be introduced in the next release with a API break.

Revert "Optimization of Entry::getItem()" (on main)

---

test/error_in_creator.cpp

Adding twice the same entry (metadata or not) will throw a exception. But we are testing async error here.
If the async error not thrown in time because the writer thread is "slow", we will not catch the async error in time and we will throw the "wrong" exception.
Should fix #775

Remove duplicated line in test/error_in_creator.

---

include/zim/search_iterator.h
src/search_internal.h
src/search_iterator.cpp
test/search_iterator.cpp

Initial cause for #773 is that `SearchIterator::InternalData::get_entry()` is getting the database number (with `get_databasenumber` which didn't check if iterator is end) before getting the document (which test for iterator).
So we were indeed throwing a exception (with `get_document`'s check) but we were doing some kind of out of bound just before. `-D_GLIBCXX_ASSERTIONS` make stdlibc++ catch that and so fail before we can throw the exception.
Fixing this, I've also fixed `getFileIndex` and `getScore`.
Even if `getSize` is not impacted by this bug, I take the occasion to depreciate it as it is useless.

Prevent dereferencing of internal xapian iterator when it is end.

---

test/search_iterator.cpp

Remove test on deprecated `getSize`.

---

.github/script/build_libzim.cmd
.github/workflows/ci.yml
subprojects/liblzma.wrap

Fix https://github.com/openzim/libzim/issues/702
This also remove a dependency to https://mirror.download.kiwix.org/dev/xz-5.2.1-wrap.zip as we now use (wrapdb) upstream wrap. (the same way we have fixed #663)
Depends of https://github.com/kiwix/kiwix-build/pull/596

Update the CI and add `aarch_dyn` target.

---

src/file_compound.h
src/zim_types.h
test/lrucache.cpp

Fixes #778 (hopefully this PR will be enough)
This PR fails on macOS because its compiler is recenter and stricter than others. The code needs to be slightly fixed to avoid the compiler complaining. Something necessary anyway if we want to move to C++14/17 like requested in #757.

Fix compilation with last xcode version

---

src/search.cpp
src/suggestion.cpp
src/writer/xapianIndexer.cpp
src/writer/xapianWorker.cpp
test/search.cpp
test/suggestion.cpp

Fix indexation of CJK languages.

---

include/zim/archive.h
include/zim/zim.h
meson.build

supercedes https://github.com/openzim/libzim/pull/792
fixes #795
try to fix the dll export issue on Windows. 
The current situation :
the dll exported is not whole ,  most of the methods have not been exported to the dll .  which is disscussed in this https://github.com/openzim/libzim/issues/795
The reason:
When put LIBZIM_EXPORT_DLL in private_conf, the generated config.h was not included in zim.h . That's why it does not work
while -DLIBZIM_EXPORT_DLL works.
The solution:
move LIBZIM_EXPORT_DLL  to public_conf which will be generate in `zim/zim_config.h`
and put the include file before the macro check

fix: dll export issue on Windows

---

src/tools.cpp
test/tooltesting.cpp

My use case is a 20Mb french text string to index, on my computer, a simple "transliterate" takes around 50 minutes to finish.
If we assume a ratio of 1/10 letter with accents, a 20 million char text would need `20M/10[number of replacement] * 20M/2[number of char to move]` moves. It is something like : `2*10^13` char moves.
By using batch of 4K, we have `4K/10*4K/2=0.8M` moves per batch. And we have `20M/4K=5000` batches.
So a total of `5000*0.8M=4G (4*10^9)`.
The ratio is 5000. So we could expect a code running 5000 times faster.
In practice, it goes from 49 minutes to 3 or 4 seconds.
@rgaudin It would be nice to know the real improvement in speed (if any) with a more common content.

Avoid working on too long strings when removing accents.

---

src/search.cpp
test/search.cpp

Fix kiwix/libkiwix#953
This is libzim (through defaultIndexer) which removing accents at indexation. We should do the same when searching.

Make search remove accents from the queried string.

---

.github/workflows/ci.yml
include/zim/archive.h
include/zim/search_iterator.h
include/zim/suggestion_iterator.h
meson.build
src/cluster.cpp
src/fileimpl.cpp
src/tools.cpp
src/writer/contentProvider.cpp
src/writer/dirent.cpp
test/archive.cpp
test/bufferstreamer.cpp
test/counterParsing.cpp
test/creator.cpp
test/defaultIndexdata.cpp
test/dirent.cpp
test/dirent_lookup.cpp
test/error_in_creator.cpp
test/find.cpp
test/lrucache.cpp
test/random.cpp
test/rawstreamreader.cpp
test/search.cpp
test/tinyString.cpp
test/tools.cpp
test/tools.h
test/tooltesting.cpp

Fix #757
All our compilers should handle c++17. Let's move on.
This PR also (re)add `werror=true` and fix different warnings (raised differently by different compilers)

Move to c++17

---

src/archive.cpp
src/dirent_lookup.h
test/archive.cpp

- `M/Counter` is not mandatory.
- zimcheck doesn't check for it.
- we already accept a missing `M/Counter` in `getArticleCount`.
No reason to fail in `getMediaCount` if `M/Counter` is missing.
We test it by reading an empty zim file.
This reveal a bug in `getNamespaceBeginOffset` when there is no dirent in the direntAccessor.
Fix kiwix/kiwix-tools#640

`getMediaCount` do not fail if `M/Counter` is missing.

---

.github/workflows/ci.yml

Better architecture and system coverage for macOS/iOS related CI

Check on all supported macOS versions

---

.github/workflows/ci.yml
.github/workflows/package.yml
meson.build
subprojects/gtest.wrap
test/compression.cpp
test/decoderstreamreader.cpp
test/error_in_creator.cpp

Fixes #829
The questions left (I see at this time) are:
* Should we update subproject/gtest
* Does that not impair compilation on older distributions (in particular focal)

Add support to recent googletest framework

---

include/zim/entry.h
include/zim/item.h
src/entry.cpp
src/item.cpp

Fixes #769
For a client of libzim the only way to create an `Item` object is through `Entry::getItem()` or `Entry::getRedirect()` (the latter relying on the former to deliver the final result).
Before this change, `Entry::getItem()` performed (via the `Item` constructor) an extra call to `FileImpl::getDirent(entry_index_t)`. Now the result of that operation that is readily available in the source `Entry` object is reused.

Reintroduce Optimization of Entry::getItem()

---

.github/workflows/ci.yml

See https://stackoverflow.com/questions/72543728/xcode-14-deprecates-bitcode-but-why
Fixes https://github.com/openzim/libzim/issues/834

Dont use bitcode as it's now deprecated

---

src/fileheader.cpp

Bump minor version and add new api to get if archive has alias.

---

include/zim/archive.h
src/archive.cpp
test/archive.cpp

Introduce new `getEntryByPathWithNamespace`

---

include/zim/archive.h
src/archive.cpp

Pr #860 removed the constructor from (fd, offset, size). This is a API break and we don't want that.

Readd removed constructor of Archive.

---

src/fileimpl.cpp

Related to #614
- I modified the FileImpl::Verify checksum algo to calculate the checksum in pieces of **1024 bytes** to save on cpu cycles and IO requests.
- Around **2.6x** fast (tested on 16 core AMD EPYC 7B13 Gitpod)
|**Size** | **Previous** | **Optimized**|
|-----------|------------------|-------------------|
31 MB    |       0.73s     |     **0.27s**   |
4 GB      |      96.84s    |     **38.17s**   |

Optimize checksum calculation on verify

---

include/zim/zim.h
src/_dirent.h
src/archive.cpp
src/dirent.cpp
src/dirent_accessor.cpp
src/dirent_accessor.h
src/entry.cpp
src/fileheader.cpp
src/fileheader.h
src/fileimpl.cpp
src/fileimpl.h
src/narrowdown.h
src/template.h
src/writer/_dirent.h
src/writer/creator.cpp
src/writer/creatordata.h
test/creator.cpp
test/dirent.cpp
test/dirent_lookup.cpp
test/find.cpp
test/header.cpp
test/iterator.cpp

Dirents' "url" are not really url. They are u8 arrays which serve as the main "key".
Specification says that this u8 array store a utf-8 encoded string and we use this key as a path.
Public API already use path semantic so rename all internal symbols from url to path.
Fix #868

Rename `*Url*` symbols to `*Path*`.

---

src/file_reader.cpp
src/file_reader.h

If we try to mmap a region to high (>4GB), `makeMmappedBuffer` will throw a `MMapException`. In this case, we want to do a read in the file instead of mmap.
This case is handled in `MultiPartFileReader` but was missing in `FileReader`.
Fix #866

Correctly handle failing mmap on FileReader.

---

src/search.cpp
src/search_internal.h
src/search_iterator.cpp
src/suggestion.cpp
src/suggestion_iterator.cpp

Either throw a ZimFileFormatError or directly handle the error (mainly returning default value or ignoring corrupted databases)
Fix #870

Catch Xapian::DatabaseError in libzim code.

---

src/file_compound.cpp
src/file_compound.h
src/fileimpl.cpp
test/archive.cpp

Fix #879 
First commit is not really related to this PR but recent gcc complain about the missing default destructor in `test/archive.cpp`. So I fix this in the same time. If you prefer, I can move it a different PR as it is not straightforward fix.

Correctly try to open split files.

---

.github/workflows/ci.yml
.github/workflows/package.yml
ChangeLog
meson.build

Release 9.2.1

---

src/buffer_reader.cpp
src/buffer_reader.h
src/file_reader.cpp
src/file_reader.h
src/fs_unix.cpp
src/fs_windows.cpp
src/reader.h
test/istreamreader.cpp
test/reader.cpp

This Pr was initially to fix #886. But it appears it was not a bug on our side.
However, it is better testing and it reveals some bug on Windows side.

Add some unittest on get_buffer

---

include/zim/zim.h
src/cluster.cpp
src/fileimpl.cpp
src/fileimpl.h
test/archive.cpp

This offset test in the cluster is to check that value parsed are consistent.
This is not to catch a potential bug in our code.
So we must throw a ZimFileFormatError in this case.
Extend the `validate` function to test this kind of corrupted offset.
Need openzim/zim-testing-suite#9
Fix #893

Correctly test invalid offsets in clusters.

---

src/file_compound.h

~~May fix #https://github.com/kiwix/kiwix-android/issues/3827 (to check).~~
Fix https://github.com/kiwix/kiwix-android/issues/3827
As describe in https://en.cppreference.com/w/cpp/algorithm/equal_range, equal_range is undefined behavior if `bool(comp(elem, value))` does not imply `!bool(comp(value, elem))`.
This is the case here for exemple with :
- value = Range{min:10, max:10}
- elem = Range{min:10, max:11}
- comp(value, elem)
=> value.min < elem.min && value.max <= elem.min
=> 10 < 10 && 10 <= 10
=> false && true
=> false
- comp(elem, value)
=> elem.min < value.min && elem.max <= value.min
=> 10 < 10 && 11 <= 10
=> false && false
=> false
`lower_bound` and `upper_bound` don't have such requirement on `comp`.

Correctly locate part range in which read data.

---

.github/workflows/package.yml

Update Packages CI/CD with latest versions of Debian/Ubuntu

---

debian/control

Replace pkg-config deb dependency with pkgconf, as pkg-config package is deprecated

Replace pkg-config deb dependency with pkgconf

---

meson.build
meson_options.txt
src/config.h.in
src/tools.cpp
src/writer/xapianIndexer.cpp
test/tooltesting.cpp

This PR is mainly a following of https://github.com/kiwix/kiwix-build/pull/715 but it is autonomous.
The flag `Compactor::FULLER` will be readd on Windows once xapian compilation on Windows using meson will be fixed.

Some fixes about window compilation

---

.github/workflows/ci.yml

We now have a compiled xapian on Windows.
We still have to workaroud a xapian/meson compilation issue by decativating "Fuller" compaction when creating db.

Make CI compile on Windows with xapian.

---

examples/meson.build
meson.build
src/meson.build
test/meson.build

Let's meson's module pkg-config generate totally our `libzim.pc` instead of trying to give smart values.

Fix meson pkgconfig

---

src/fs_unix.cpp

pread64(3) is Linux-specific and not declared on other platforms

---

src/file_reader.cpp

https://www.man7.org/linux/man-pages/man2/mmap.2.html
https://man.netbsd.org/mmap.2

MAP_POPULATE is Linux-specific and not declared on other platforms

---

.github/workflows/ci.yml

Stop building with debug symbols on Windows

---

scripts/download_test_data.py
src/fileheader.cpp
src/fileheader.h
src/fileimpl.cpp
src/fileimpl.h
src/tools.cpp
src/tools.h
src/writer/_dirent.h
src/writer/creator.cpp
src/writer/creatordata.h
src/writer/dirent.cpp
src/writer/titleListingHandler.cpp
src/writer/titleListingHandler.h
src/writer/xapianHandler.cpp
test/archive.cpp
test/creator.cpp
test/find.cpp
test/iterator.cpp
test/tools.cpp
test/tools.h

Fix #800
This PR needs testing files from https://github.com/openzim/zim-testing-suite/pull/13
(and a release of zim-testing-suite project to be correctly used here) and so, CI is failing (as expected).
The simpler for locally testing this PR is to copy https://github.com/openzim/zim-testing-suite/tree/no_v0/data/nov0 into you local zim-testing-suite v0.6.0 directory.
An important change is that `listing/titleOrdered/v1` is now created all the time, even if there is no front article.
This means that there will be no fallback to "all entries" (random, suggestion without xapian) when creator do not properly set front articles.
This case is really rare as we automatically mark item as front article if mimetype starts with "text/html" when no hint is given.

Remove listing/titleOrdered/v0.

---

src/suggestion.cpp
test/suggestion.cpp

Fixes kiwix/kiwix-desktop#1345

Fixed suggestions for a single-word-followed-by-space query

---

src/tools.h
src/writer/tinyString.h

Making undefined behavior sanitizer happy with tinyString.h
Closes #954

954 ubsan tinystring

---

src/tools.h
src/writer/tinyString.h

This reverts commit e152b1daa73a0b372b4788a1e5b1cb36d651f45c.
Fixes #962

Revert "Fix #954. safe_memcmp in tinystring."

---

src/fileheader.cpp
src/fileheader.h
src/fileimpl.cpp
src/writer/creator.cpp
test/creator.cpp

Fixes #800
Absence of the title index v0 is now signaled via the titleIdxPos set to 0xffffffffffffffff instead of 0 since the latter resulted in ZIM files incompatible with older versions of libzim. Several such ZIM files have found home in zim-testing-suite (v 0.7.0) and have to be replaced. In theory, each of those ZIM files could be patched with a few bytes in two locations (titleIdxPos in the ZIM file header and the checksum at the end of the file). An easier solution is to recreate them, but I don't want it to be done with a locally built version of zim-tools (like it was done in openzim/zim-testing-suite#13 which references a libzim commit that was eventually edited/replaced during the review/rebase of PR #949 and is no longer part of the main branch).  That's why …

Backward compatibility of title index v0 removal

---

src/writer/_dirent.h
src/writer/tinyString.h
src/writer/xapianHandler.cpp
test/suggestion.cpp
test/tinyString.cpp

Fixed title indexing of items with title identical to the item's path

---

scripts/download_test_data.py
src/fileheader.cpp

@veloman-yunkan can you please fix/adapt the code to this, review en merge?

Use latest zim-testing-suite

---

docs/usage.rst
include/zim/archive.h
include/zim/entry.h
include/zim/item.h
include/zim/search.h
include/zim/search_iterator.h
include/zim/zim.h
src/archive.cpp
src/entry.cpp
src/fileimpl.cpp
src/fileimpl.h
src/item.cpp
src/lock.h
src/search.cpp
src/search_internal.h
src/search_iterator.cpp
src/suggestion.cpp
src/tools.cpp
src/tools.h
test/archive.cpp

Fix https://github.com/openzim/libzim/issues/617 (preloading xapian database)
Numbers do not show a strong win (not a lost neither) but this PR also introduce nice improvement as side effect and so is a good preparatory work for next project about multi zim and multi lang issues.
Globally this PR does:
- Move xapian metadata out of internalDataBase
- Separate xapian database (and metadata) from internalDataBase. `XapianDb` is about a specific database stored in a zim file. `InternalDataBase` is about a database we search in (which "include" `XapianDb`s)
- Move opening of xapian database in fileImpl (on the archive side instead of on the search side)
- Open only on xapian db per archive. This as the side effect that searching is now thread safe. (We introduce mutex lock system to do so)
- …

Preload Xapian database

---

src/namedthread.cpp
src/namedthread.h

Fixed the race condition in NamedThread

---

test/log.cpp

Should fix #986
The effect of this PR on the `kiwix-build` CI was tested in kiwix/kiwix-build#825. There were two successful workflow runs ([1](https://github.com/kiwix/kiwix-build/actions/runs/14858923355/attempts/1?pr=825), [2](https://github.com/kiwix/kiwix-build/actions/runs/14858923355?pr=825)) suggesting that the fix works.

More stable Log.concurrencyOrchestration unittest

---

test/counterParsing.cpp
test/defaultIndexdata.cpp
test/error_in_creator.cpp
test/parseLongPath.cpp

`counterParsing`
- replace macro with global variable
`defaultIndexdata`
- replace arithmetic operations with floating point comparison macro
`error_in_creator`
- reduce duplication of template test parameters as described in the comment
`parseLongPath`
- succinct assertions using tuple value comparisons

Some clean-up in test code

---

include/zim/suggestion.h
include/zim/suggestion_iterator.h
src/smartptr.h
src/suggestion.cpp
src/suggestion_internal.h
src/suggestion_iterator.cpp
src/tools.h
test/suggestion.cpp
test/tools.cpp
test/tools.h

This is the clean-up work extracted from #994

Cleanup of suggestions code

---

.github/workflows/ci.yml

Move the whole CI to macOS 15, which implies updated compilation stack and full (botch arch+system) cross-compilation for x86_64 arch.

Use macOS 15 for CI

---

meson.build

Due to unicode-org/icu@199bc82, ICU 76 no longer adds `icu-uc` by default. This causes linker errors for undefined symbols like `icu_76::UnicodeString::doReplace(...)`, referenced from: `zim::removeAccents(...)` in tools.cpp.o.
Meson will automatically flatten the dependencies list as documented at https://mesonbuild.com/Reference-manual_functions.html#build_target
This PR superseeds #936

Fix build with ICU 76
