README, README.md
=> README for Meson #5

include/zim/template.h, include/zim/writer/articlesource.h, src/fstream.cpp
gcc reports some warning, and they are bug actually.
Let's fix them.
=> Fix compilation warning.

include/zim/search.h, src/search.cpp, src/search_iterator.cpp
It was silly to not handle it at first glance.
This should fix the crash of : https://github.com/kiwix/kiwix-tools/issues/30 and https://github.com/kiwix/kiwix-tools/issues/28
And maybe https://github.com/kiwix/kiwix-tools/issues/25
=> Handle the case when zim file has no embedded full text index database.

include/zim/search_iterator.h, src/search_internal.h, src/search_iterator.cpp
We need somehow to get in which file the search result article is.
=> Add get_fileIndex to search iterator to get associated file of a result.

meson.build, subprojects/gtest.wrap, test/cluster.cpp, test/dirent.cpp, test/header.cpp, test/meson.build, test/template.cpp, test/uuid.cpp, test/zint.cpp, travis/compile.sh, travis/install_deps.sh
Add google-test (gtest) as subproject.
Tests have not changed. They have just been moved to new test framework.
=> Move to google-test instead of cxxtools.

src/tools/meson.build, src/tools/zimBench.cpp
This way, we don't use cxxtools at all.
=> Make zimBench not use cxxtools.

include/zim/article.h, src/article.cpp, src/cluster.cpp, src/cluster.h
This is needed to have kiwix-server respond to http bytes-range.
=> Add methods to get only a part of an article.

travis/compile.sh
It is kiwix-lib that must be compiled shared.
=> On android, libzim must be compiled statically.

meson.build, src/config.h.in, src/file_reader.cpp, src/meson.build, src/writer/cluster.cpp, src/writer/zimcreatorimpl.cpp, test/cluster.cpp
Should fix https://github.com/openzim/zimwriterfs/issues/18 and https://github.com/openzim/sotoki/issues/66
=> Zlib lzma fix

src/search.cpp
Some function are used only if we are compiling libzim with xapian
support.
As we are compiler libzim with `-Werror`, we should not have defined but
not used function.
Let's move function definition in the correct `ENABLE_XAPIAN` guard.
Fix #66.
=> Define function used by "xapian method" only when xapian is used.

README.md
=> Update README to add missing dependencies' information.

src/writer/zimcreatorimpl.cpp
This step can take days... and then nothing is written at all on the console.
=> More redirect cleaning messages if --verbose

src/search.cpp
We should check that open function correctly open the file without error.
=> [Search] Correctly check that the zimfile name has been correctly opened

src/search.cpp
We have a lot of crashes when trying to open the database.
It would be better to know why but for now, do not crash.
Related to kiwix/kiwix-tools#153
=> Do not crash if something went wrong when opening the database.

src/search.cpp
Improve the search and suggestion.
Should fix kiwix/kiwix-tools#162
=> Better search

test/cluster.cpp
Use low level function (using off_t for offset) instead of stream api
(using long for offset)
=> Fix test of cluster.

.travis.yml, travis/install_deps.sh
Also try to speed up a bit the build by :
- Do not use sudo
- Use prebuild ninja binary.
=> Build libzim on macos.

test/meson.build
=> Extend tests timeout #147

test/cluster.cpp
=> Fix a few test compilation warnings #148

src/writer/cluster.cpp, src/writer/cluster.h, test/cluster.cpp
=> Test uses less memory

ChangeLog, src/tools.cpp, src/tools.h, src/writer/zimcreator.cpp
=> Rename ZIM file to *.zim at the end #163

README.md
@mgautierfr What do you think of that? If OK, I plan to use it as a base for https://github.com/openzim/zimwriterfs/issues/46 and will also update the one for libkiwix and kiwix-tools.
=> Simplify compilation instructions

.travis.yml, src/xapian/myhtmlparse.cc
See kiwix/kiwix-build@2a18f74786fd99585c642ba3599dd46d73827807
=> Do not build with gcc5.

src/fileimpl.cpp
=> Catch exceptions by reference.

src/file_reader.cpp
Sometime, we fail to read in zim part.
We better error message, it will be easier to do post-mortem debugging.
=> Better error message when failing to read in zim file.

src/writer/xapianIndexer.h
Fix openzim/zimwriterfs#35
See openzim/zimwriterfs#40
=> Store the xapian database using the right url.

src/writer/creator.cpp
=> Add some more debug output to have information about the current step.

src/writer/creator.cpp
=> Print the advancement of clusters written in the zim file.

.codecov.yml, .travis.yml, travis/compile.sh, travis/install_deps.sh
=> Add code coverage and upload it to codecov.

src/writer/cluster.cpp
=> Always use the best compression level with lzma.

examples/createZimExample.cpp, include/zim/article.h, include/zim/writer/creator.h, src/article.cpp, src/meson.build, src/writer/creator.cpp, src/writer/creatordata.h, src/writer/workers.cpp, src/writer/workers.h, src/writer/xapianIndexer.cpp, src/writer/xapianIndexer.h
=> Xapian thread

src/writer/creator.cpp
=> Index title only if `shouldIndex` return true.

travis/install_deps.sh
Simple fix for travis builds on macos. tested.
=> Fixed macos build failing due to broken wget

.github/workflows/pr.yml
Use a the codecov action to upload the code coverage result.
=> Fix codecov.

test/cluster.cpp, test/dirent.cpp, test/header.cpp
No real mistake here, just use the windows functions to create the
temporary file.
=> Fix tests on windows.

.codecov.yml
Following https://github.com/openzim/libzim/pull/321#issuecomment-617613442
@veloman-yunkan Something like this?
=> Fix codecov configuration for PRs

src/writer/creator.cpp
=> [Writer] Use a tmp file and rename to the right name at the end.

src/writer/cluster.cpp, src/writer/cluster.h, src/writer/workers.cpp
=> Clear data from cluster when we don't need it.

src/fileimpl.cpp
=> Do not assume urlPtrPos is just after mimeList when reading it.

test/compression.cpp
Also add test on ZLIB compression.
Fix #352
=> Conditionally compile compression test if algorithm is supported.

.github/workflows/package.yml
Per discussion with Kelson on IRC, we're renaming the PPAs to be just "dev" and "release".
=> Update PPA names

src/_dirent.h, src/article.cpp, src/cluster.cpp, src/dirent.cpp, src/fileimpl.cpp, src/zim_types.h, test/dirent.cpp
This PR contains some primitive improvements made to the libzim source code while studying it in the context of https://github.com/openzim/libzim/projects/2.
=> Exploratory refactoring of libzim

include/zim/file.h, src/cluster.cpp, src/cluster.h, src/file.cpp, src/file_compound.cpp, src/file_compound.h, src/file_reader.cpp, src/fileimpl.cpp, src/fileimpl.h
This PR is a by-product of an in-depth study of the libzim source code (a sequel of #351).
=> Exploratory cleanup

src/cluster.h
Addressing one of the screwups described in https://github.com/openzim/libzim/pull/393#issuecomment-677670354
=> Fixed wrong comment

src/cluster.cpp, src/cluster.h
=> Validate the blob index to avoid crash

include/zim/writer/item.h, src/archive.cpp, src/entry.cpp, src/fileheader.cpp, src/fileimpl.cpp, src/fileimpl.h, src/item.cpp, src/tools.cpp, src/tools.h, src/writer/creator.cpp, src/writer/creatordata.h, test/meson.build, test/parseLongPath.cpp
This is the "final" PR of the (first) level of libzim next.
With it libzim will create zim file totally hiding the namespace.
Need #402 being merged first.
=> New namespace scheme.

.github/workflows/ci.yml, README.md, examples/meson.build, include/zim/zim.h, meson.build, src/cluster.cpp, src/compression.cpp, src/compression.h, src/config.h.in, src/meson.build, src/writer/cluster.cpp, test/cluster.cpp, test/compression.cpp, test/decoderstreamreader.cpp
=> Remove zlib dependency.

include/zim/archive.h, include/zim/writer/creator.h, src/archive.cpp, src/fileimpl.cpp, src/fileimpl.h, src/search.cpp, subprojects/liblzma.wrap
Few fixes and improvement related to libzim_next and api.
=> Fixes related to libzim next

include/zim/writer/creator.h, src/writer/creator.cpp
=> Made Zstd the default compression

include/zim/writer/creator.h, include/zim/writer/item.h, src/cluster.h, src/dirent_accessor.cpp, src/fileimpl.cpp, src/fileimpl.h, src/meson.build, src/writer/_dirent.h, src/writer/cluster.cpp, src/writer/cluster.h, src/writer/creator.cpp, src/writer/creatordata.h, src/writer/handler.h, src/writer/item.cpp, src/writer/titleListingHandler.cpp, src/writer/titleListingHandler.h, src/writer/xapianHandler.cpp, src/writer/xapianHandler.h, test/archive.cpp, test/creator.cpp
This is the second PR corresponding to the split of #466
Based on ~~#486~~ #493
- Change the creation behavior (add ~~wellknown entries and~~ index)
- Change reading behavior (read new entries)
- Update tests.
=> Move title indexes in a zim Entry.

README.md
=> Update README to add instruction to compile without xapian.

debian/changelog, debian/control
=> PPA: Rename source package to "libzim"

include/zim/search.h, include/zim/search_iterator.h, src/search.cpp, src/search_internal.h, src/search_iterator.cpp, test/search.cpp, test/search_iterator.cpp, test/suggestion.cpp
Fixes #562 
Changes included in this pr:
- Move the search iterator API to use camel case 
- Fix libzim internally to use this new scheme
=> Search iterator should be made camelcase

src/compression.cpp, src/compression.h, src/concurrent_cache.h, src/decoderstreamreader.h, src/lrucache.h, test/lrucache.cpp
This is the same PR than #568 but backported on 6.3 branch (tag 6.3.0)
=> Check decompression status in DecoderStreamReader. 6.3

meson.build, src/compression.cpp, src/concurrent_cache.h, src/config.h.in, src/fileimpl.cpp
This is the same PR than #569 but backported on 6.3 branch (tag 6.3.0)
=> Lower zstd compression level. 6.3

include/zim/archive.h, include/zim/writer/item.h, src/archive.cpp, src/fileimpl.h, test/archive.cpp, test/iterator.cpp, test/tools.h
=> Better methods to get number of entries in a zim archive.

docs/requirements.txt
=> [CI] Force sphinx version<4 to build the documentation.

test/tools.h
=> Fix write_to_buffer on MacOS.

src/archive.cpp, src/tools.cpp
=> Fix two small warnings.

examples/createZimExample.cpp, include/zim/archive.h, include/zim/search.h, include/zim/writer/creator.h, include/zim/zim.h, src/archive.cpp, src/cluster.cpp, src/cluster.h, src/fileimpl.cpp, src/search.cpp, src/writer/cluster.cpp, src/writer/cluster.h, src/writer/creator.cpp, src/writer/creatordata.h, test/archive.cpp, test/cluster.cpp, test/creator.cpp, test/dirent.cpp, test/search.cpp, test/search_iterator.cpp, test/suggestion_iterator.cpp
=> Fix some small imperfections in the API.

src/debug.h
=> Alipine musl compilation fix

include/zim/archive.h, include/zim/writer/creator.h, include/zim/writer/item.h, src/archive.cpp, src/fileimpl.cpp, src/writer/creator.cpp, src/writer/item.cpp, src/writer/titleListingHandler.cpp, src/writer/xapianHandler.cpp, src/writer/xapianHandler.h, test/archive.cpp, test/find.cpp, test/indexing_criteria.cpp, test/meson.build, test/suggestion.cpp, test/tools.h
=> Index criteria

src/debug.h
=> Fix Emscripten compilation

README.md
=> Update README.md to reflect docs build deps

.github/workflows/ci.yml, meson.build
Read https://mesonbuild.com/Cross-compilation.html for all the rationals.
=> Use "host_machine", not "target_machine" for cross-compilation

include/zim/writer/creator.h
=> Set default mimetype for creator.addMetadata

include/zim/archive.h, include/zim/blob.h, include/zim/entry.h, include/zim/item.h
=> Add some information about thread safety in docstring.

include/zim/writer/creator.h, src/writer/creator.cpp, test/creator.cpp
=> Do not handle "not added" or removed dirent.

src/suggestion.cpp, test/suggestion.cpp
=> Diacritics insensitive suggestions

.github/workflows/ci.yml
=> Run the CI on Ubuntu Bionic and Fedora 35

README.md
See https://github.com/openzim/libzim/issues/680#issuecomment-1139368862
=> Libzim does not depend on libuuid

.github/workflows/ci.yml
This is a PR to fix the android compilation in the CI (instead of hijacking the pr #710)
=> Fix android compilation in the CI

.github/workflows/package.yml
~~Note: launchpad is still setting up "kinetic" on our PPA so CI is failing. I'll kick it again in an hour or two and it hopefully will pass.~~ Done!
=> PPA: Drop impish, add kinetic

AUTHORS
I have kept only the most significant contributors
=> Updated AUTHORS file

include/zim/zim.h, src/cluster.cpp, src/cluster.h, src/compression.cpp, src/compression.h, src/fileimpl.cpp, src/writer/cluster.cpp, src/writer/creator.cpp, test/cluster.cpp, test/compression.cpp, test/creator.cpp, test/decoderstreamreader.cpp
=> End of support for LZMA compression in writer

src/writer/creator.cpp
=> Allocated more space for mimetypes list

ChangeLog, meson.build
=> New version 8.0.0

src/tools.cpp
Moving setICUDataDirectory inside zim namespace
=> Moving setICUDataDirectory inside zim namespace

include/zim/writer/contentProvider.h, include/zim/writer/item.h
Light improvement of codefactor report.
=> Remove empty lines

ChangeLog, meson.build
* Optimization ofthe first call to `zim::Archive::iterEfficient` (@veloman-yunkan #724)
* Add some documentation to `zim::writer::IndexData` (@mgautierfr #727)
* Correctly catch and rethrow exception thrown in worker threads at creation (@mgautierfr #496 #748)
* Optimization of `Entry::getItem()` (@veloman-yunkan #732)
* Fix declaration of `zim::setICUDataDirectory()` (@MohitMaliFtechiz #733)
* Add `zim::Archive::getMediatCount()` (@mgautierfr #730)
* Make compilaton of examples optional (@mgautierfr #738)
* Add a CI for wasm (@mgautierfr #746)
* Make constructor of SuggestionItem public (@veloman-yunkan #740)
=> New version 8.1.0

src/suggestion.cpp, src/writer/xapianIndexer.cpp, test/suggestion.cpp, test/tools.cpp
=> Suggesting articles with titles made of punctuation only

.github/workflows/ci.yml, .github/workflows/package.yml
* Avoid calling twice CI/Packages workflow
* Use new CI image containers
* Use `actions/checkout`
* Multiple other simplification
Depends on https://github.com/kiwix/kiwix-build/pull/566 (and a new release has to be made)
=> Multiple CI improvements

.github/workflows/package.yml
=> Remove CI bionic package.

.github/workflows/ci.yml
Use Github Actions Workflow in place of downloading a bash script
=> Use Codecov action

.github/workflows/ci.yml, .github/workflows/package.yml
* Use versin 38 of CI container base images
* use pinned version of CD packages
=> Use latest CI container image v38

ChangeLog, meson.build
Partly solved #823:
* meson version updated
* Changelog updated
=> Release 9.0.0

meson.build, meson_options.txt
=> Allow to disable test build

src/file_reader.cpp, src/fs_unix.cpp
Had this patch lying around for a while and with checking up on latest version it still applies, hence a request for a merge. :)
=> Haiku build fix

ChangeLog, meson.build
~~Draft as we may want to merge #873 first.~~ #873 is merged.
=> New version 9.2.0

src/file_compound.cpp, src/file_compound.h, test/archive.cpp
=> Better error message when failin to open (split) zim file.

ChangeLog, meson.build
=> Release 9.2.2

.github/workflows/package.yml
=> fix ubuntu-noble package step

.github/workflows/package.yml
=> Simplify package step for Ubuntu builds

.github/workflows/ci.yml
=> Add windows-2022 to CI

.github/workflows/package.yml
This reverts commit c11bc270f8c6141483b6dc24ab5750919a06b02d.
=> Revert "Simplify even more deb package CI/CD"

README.md
=> Document windows usage

ChangeLog, meson.build
=> Release 9.2.3

.github/workflows/ci.yml
Update with latest version of the OSSF CI check
=> Update OSSF CI action

ChangeLog, meson.build
New version and upadted changelog
=> Release 9.3.0

test/concurrentcache.cpp, test/lrucache.cpp, test/meson.build
=> A separate unit-test for ConcurrentCache

src/log.cpp, src/log.h, src/meson.build, src/namedthread.cpp, src/namedthread.h, test/log.cpp, test/meson.build
This PR introduces the `log_debug_XXX()` utilities serving as whitebox testing tools for unit-testing of ConcurrentCache in #960
=> Log debug utils
